package com.scopely.mapper;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import org.inferred.freebuilder.FreeBuilder;

import java.util.Optional;

@FreeBuilder
@JsonDeserialize(builder = HashAndOptionalRange.Builder.class)
@DynamoDBTable(tableName = "hash_and_range")
interface HashAndOptionalRange {
    @DynamoDBHashKey(attributeName = "hashKey")
    String getHashKey();
    @DynamoDBAutoGeneratedKey
    @DynamoDBRangeKey(attributeName = "rangeKey")
    Optional<String> getRangeKey();

    class Builder extends HashAndOptionalRange_Builder {}
}
