
package com.scopely.mapper;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import org.inferred.freebuilder.FreeBuilder;

import java.util.Optional;

@FreeBuilder
@JsonDeserialize(builder = InvalidRange.Builder.class)
@DynamoDBTable(tableName = "hash_and_range")
interface InvalidRange {
    @DynamoDBHashKey(attributeName = "hashKey")
    String getHashKey();
    @DynamoDBAutoGeneratedKey
    @DynamoDBRangeKey(attributeName = "rangeKey")
    Optional<Long> getRangeKey();

    class Builder extends InvalidRange_Builder {}
}
